Autolib/Autolib/Controllers/ConnexionController.cs
using Autolib.Models.Dao;
using Autolib.Models.Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMangaEntity.Models.Utilitaires;

namespace Autolib.Controllers
{
    public class ConnexionController : Controller
    {
        ServiceClient sc = ServiceClient.getInstance();
        // GET: ConnexionController
        public ActionResult Index()
        {
            if (HttpContext.Session.GetInt32("id") > 0)
            {
                HttpContext.Session.Clear();
                return RedirectToAction("Index", "Home");
            }
            return View();
        }

        // GET: ConnexionController/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ConnexionController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ConnexionController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ConnexionController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ConnexionController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: ConnexionController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ConnexionController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
        [HttpPost]
        public ActionResult Controle()
        {
            try
            {
                // on récupère les données du formulaire
                String login = Request.Form["username"];
                String mdp = Request.Form["password"];
                try
                {

                    Client unUtilisateur = ServiceClient.getInstance().GetClient(login);
                    if (unUtilisateur != null)
                    {
                        try
                        {
                            if (sc.CheckClient(login, mdp))
                            {
                                HttpContext.Session.SetInt32("id", unUtilisateur.IdClient);
                                HttpContext.Session.SetString("nom", unUtilisateur.Nom + " " + unUtilisateur.Prenom);
                            }
                            else
                            {
                                ModelState.AddModelError("Erreur", "Erreur lors du contrôle  du mot de passe pour : " + login);
                                return View("Index", "Erreur lors du contrôle  du mot de passe pour : " + login);
                            }
                        }
                        catch (Exception e)
                        {
                            ModelState.AddModelError("Erreur", "Erreur lors du contrôle : " + e.Message);
                            return View("Index", "Erreur lors du contrôle : " + e.Message);
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Erreur", "Erreur  login erroné : " + login);
                        return View("Index", "Erreur  login erroné : " + login);
                    }
                }
                catch (Exception e)
                {
                    ModelState.AddModelError("Erreur", "Erreur lors de l'authentification : " + e.Message);
                    return View("Index", "Erreur lors de l'authentification : " + e.Message);
                }
                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                ModelState.AddModelError("Erreur", "Erreur lors de l'authentification : " + e.Message);
                return View("Index", "Erreur lors de l'authentification : " + e.Message);
            }
        }

    }
}

Autolib/Autolib/Views/Connexion/Index.cshtml
@{
    ViewData["Title"] = "Contact";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="col-sm-12 ml-auto mr-auto" id="signincontent">
    @if (Model != null)
    {
        <div class="col-12 alert alert-danger">
            @Model
        </div>
    }
    <ul class="nav nav-pills nav-fill mb-1" id="pills-tab" role="tablist">
        <li class="nav-item"> <a class="nav-link active" id="pills-signin-tab" data-toggle="pill" href="#pills-signin" role="tab" aria-controls="pills-signin" aria-selected="true">Se connecter</a> </li>
        <li class="nav-item"> <a class="nav-link" id="pills-signup-tab" data-toggle="pill" href="#pills-signup" role="tab" aria-controls="pills-signup" aria-selected="false">S'inscrire</a> </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-signin" role="tabpanel" aria-labelledby="pills-signin-tab">
            <div class="col-sm-12 border border-primary shadow rounded pt-2" id="card-signin">
                <form method="post" id="singninFrom" action="@Url.Action("Controle", "Connexion")">
                    <div class="form-group">
                        <label class="font-weight-bold">identifiant <span class="text-danger">*</span></label>
                        <input type="texte" name="username" id="username" class="form-control" placeholder="Rentrer votre identifiant" required>
                    </div>
                    <div class="form-group">
                        <label class="font-weight-bold">Mot de passe <span class="text-danger">*</span></label>
                        <input type="password" name="password" id="password" class="form-control" placeholder="***********" required>
                    </div>
                    <div class="form-group">
                        <input type="submit" name="submit" id="signupsubmit" value="Se connecter" class="btn btn-block btn-primary">
                    </div>
                </form>
            </div>
        </div>
        <div class="tab-pane fade" id="pills-signup" role="tabpanel" aria-labelledby="pills-signup-tab">
            <div class="col-sm-12 border border-primary shadow rounded pt-2" id="card-signin">
                <form method="post" id="singnupFrom" action="@Url.Action("Create","Clients")">
                    <div class="form-group">
                        <label class="font-weight-bold">Prénom <span class="text-danger">*</span></label>
                        <input type="text" for="Prenom" name="signupforname" id="signupforname" class="form-control" placeholder="Prénom" required onkeypress="return(testString(event));">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-bold">Nom <span class="text-danger">*</span></label>
                        <input type="text" for="Nom" name="signupname" id="signupname" class="form-control" placeholder="nom" required onkeypress="return(testString(event));">
                    </div>
                    <div class="form-group">
                        <label class="font-weight-bold">Nom d'utilisateur <span class="text-danger">*</span></label>
                        <input type="text" for="Login" name="signupusername" id="signupusername" class="form-control" placeholder="Choississez votre identifiant" required>
                        <div class="text-danger"><em>Ce sera votre identifiant de connexion !</em></div>
                        <div class="form-group">
                            <div class="form-group">
                                <label class="font-weight-bold">Date de naissance<span class="text-danger">*</span></label>
                                <input type="datetime-local" id="naissance"
                                       name="naissance" required />
                                <div class="form-group">
                                    <label class="font-weight-bold">Mot de passe<span class="text-danger">*</span></label>
                                    <input type="password" for="Paswd" name="signuppassword" id="signuppassword" class="form-control" placeholder="***********" pattern="^\S{6,}$" onchange="this.setCustomValidity(this.validity.patternMismatch ? 'Doit avoir au moins 6 caractères' : ''); if(this.checkValidity()) form.password_two.pattern = this.value;" required>
                                </div>
                                <div class="form-group">
                                    <label class="font-weight-bold">Confirmer votre Mot de passe<span class="text-danger">*</span></label>
                                    <input type="password" name="signupcpassword" id="signupcpassword" class="form-control" pattern="^\S{6,}$" onchange="this.setCustomValidity(this.validity.patternMismatch ? 'Please enter the same Password as above' : '');" placeholder="***********" required>
                                </div>
                                <div class="form-group">
                                    <input type="submit" name="signupsubmit" id="signupsubmit" value="S'inscrire" class="btn btn-block btn-primary">
                                </div>
                </form>
            </div>
        </div>
    </div>
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
<script>
    Date.prototype.addHours = function (h) {
        this.setTime(this.getTime() + (h * 60 * 60 * 1000));
        return this;
    }

    var confignaissance = {
        enableTime: false,
        altInput: true,
        

        altFormat: "d-m-Y",
        dateFormat: "Y-m-dTH:i",
        maxDate: new Date().fp_incr(-1),

    }

    startPicker = flatpickr("#naissance", confignaissance);



</script>